const questions = [
    {
        "question": "문제를 인식하고 해결하는 것에 자신있습니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
            "desk": 1.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
            "mle": 1.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
 },
    {
        "question": "새로운 환경에 곧잘 적응합니다.",
        "effect": {
            "front": 1.0,
             "back": 0.0,
             "desk": 0.0,
            "mobile": 1.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
            "what": 1.0,
             "ma": 0.0,
            "iot": 0.0,
        }
 },
    {
        "question": "압박감이 심한 상황에서도 침착함을 유지합니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
            "gserver": 1.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
            "what": 1.0,
             "ma": 0.0,
             "iot": 0.0,
        }
},
    {
        "question": "논리적으로 분석하는 것에 자신있습니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
            "bigdb": 1.0,
             "mle": 0.0,
             "what": 0.0,
            "ma": 1.0,
             "iot": 0.0,
        }
},
    {
        "question": "종종 주변을 잊어버리는 생각에 빠지곤 합니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
            "ma": 1.0,
             "iot": 0.0,
        }
},
    {
        "question": "타인과의 약속은 잘 지켜야 한다고 생각합니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
            "what": 1.0,
            "ma": 1.0,
             "iot": 0.0,
        }
},
    {
        "question": "새로운 아이디어를 떠올리는 것을 좋아합니다",
        "effect": {
            "front": 1.0,
             "back": 0.0,
            "desk": 1.0,
            "mobile": 1.0,
             "model": 0.0,
             "uiux": 0.0,
            "gclient": 1.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
            "iot": 1.0,
        }
},
    {
        "question": "사람을 만나고 의사소통하는 것을 좋아합니다.",
        "effect": {
            "front": 1.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
 },
    {
        "question": "트렌드와 사람들의 니즈를 잘 파악합니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
            "desk": 1.0,
            "mobile": 1.0,
             "model": 0.0,
            "uiux": 1.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
},
    {
        "question": "집 꾸미는 것에 관심이 있습니다.",
        "effect": {
            "front": 1.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
            "model": 1.0,
            "uiux": 1.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
            "iot": 1.0,
        }
},
    {
        "question": "평소 SNS를 활발하게 이용합니다.",
        "effect": {
            "front": 1.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
},
    {
        "question": "평소 규칙적이고 계획적인 생활을 합니다. ",
        "effect": {
            "front": 1.0,
            "back": 1.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
},
    {
        "question": "프로그램 작동 원리에 대해 깊이 생각합니다.",
        "effect": {
             "front": 0.0,
            "back": 1.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
},
    {
        "question": "나만의 소프트웨어를 상상해본적이 있습니다.",
        "effect": {
             "front": 0.0,
            "back": 1.0,
             "desk": 0.0,
             "mobile": 0.0,
            "model": 1.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
            "iot": 0.0,
        }
},
    {
        "question": "다른사람을 돕는것에 관심이 많습니다.",
        "effect": {
             "front": 0.0,
            "back": 1.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
            "gserver": 1.0,
            "dbm": 1.0,
             "bigdb": 0.0,
            "mle": 1.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
},
    {
        "question": "평소 PC방을 자주 이용합니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
            "desk": 1.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
            "gclient": 1.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
},
    {
        "question": "평소 단축키를 자주 활용하는 편입니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
            "desk": 1.0,
             "mobile": 0.0,
            "model": 1.0,
            "uiux": 1.0,
            "gclient": 1.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
},
    {
        "question": "본인 컴퓨터를 자주 포맷하는 편입니다.",
        "effect": {
             "front": 0.0,
            "back": 1.0,
            "desk": 1.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
            "gserver": 1.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
 },
    {
        "question": "하루에 10개 이상의 어플을 사용합니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
            "mobile": 1.0,
             "model": 0.0,
            "uiux": 1.0,
            "gclient": 1.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
},
    {
        "question": "다른사람에게 새로운 앱을 추천합니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
            "mobile": 1.0,
             "model": 0.0,
            "uiux": 1.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
            "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
},
    {
        "question": "새로운 어플들에 대해서 잘 알고 있습니다.",
        "effect": {
            "front": 1.0,
             "back": 0.0,
             "desk": 0.0,
            "mobile": 1.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
},
    {
        "question": "문제의 원인에 대해 깊이 생각해 봅니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
            "bigdb": 1.0,
            "mle": 1.0,
            "what": 1.0,
            "ma": 1.0,
             "iot": 0.0,
        }
},
    {
        "question": "확률이 사회 현상을 설명할 수 있습니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
            "bigdb": 1.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
},
    {
        "question": "통계가 세상의 모든것을 말해줄 수 있습니다",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
            "bigdb": 1.0,
            "mle": 1.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
 },
    {
        "question": "원인보다는 결과가 더 중요하다고 생각합니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
            "mle": 1.0,
            "what": 1.0,
            "ma": 1.0,
             "iot": 0.0,
        }
},
    {
        "question": "귀차니즘이 내 머릿속을 지배하고 있습니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
            "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
            "iot": 1.0,
        }
},
    {
        "question": "기계가 내 일을 대신 해줬으면 좋겠습니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
            "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
            "iot": 1.0,
        }
},
    {
        "question": "휴대폰 업데이트를 자주 하는 편입니다. ",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
            "what": 1.0,
            "ma": 1.0,
             "iot": 0.0,
        }
},
    {
        "question": "스스로를 계획적인 사람이라고 생각합니다.",
        "effect": {
             "front": 0.0,
            "back": 1.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
            "gserver": 1.0,
            "dbm": 1.0,
             "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
},
    {
        "question": "평소 주변 정리를 자주 하는 편입니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
            "dbm": 1.0,
             "bigdb": 1.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
},
    {
        "question": "평소 제품 디자인에 관심이 많습니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
            "model": 1.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
},
    {
        "question": "공간 지각 능력이 뛰어나다고 생각합니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
            "model": 0.0,
             "uiux": 0.0,
             "gclient": 0.0,
             "gserver": 0.0,
            "dbm": 1.0,
            "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
},
    {
        "question": "한번 가본 길을 잘 기억하는 편입니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
             "model": 0.0,
            "uiux": 1.0,
             "gclient": 0.0,
             "gserver": 0.0,
            "dbm": 0.0,
            "bigdb": 1.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
},
    {
        "question": "평소 게임을 즐겨 하는 편입니다.",
        "effect": {
             "front": 0.0,
             "back": 0.0,
             "desk": 0.0,
             "mobile": 0.0,
            "model": 1.0,
             "uiux": 0.0,
            "gclient": 1.0,
            "gserver": 1.0,
             "dbm": 0.0,
             "bigdb": 0.0,
             "mle": 0.0,
             "what": 0.0,
             "ma": 0.0,
             "iot": 0.0,
        }
    }
];

export default questions